name: Update README with Blog Posts

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README content
        run: |
          posts=$(ls *.md 2>/dev/null)
          if [ -z "$posts" ]; then
            echo "No .md files found." > README.md
          else
            echo "# 我的博客" > README.md
            echo "" >> README.md
            echo "这里是我在 GitHub 上的博客文章列表：" >> README.md
            echo "" >> README.md
            for post in $posts; do
              echo "- [$(basename "$post")](./$post)" >> README.md
            done
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README with blog posts"
          branch: main
