name: Update README with MD Files

on:
  push:
    paths:
      - "*.md"
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          # 获取所有 .md 文件（排除 README.md）
          md_files=$(find ./ -maxdepth 1 -name "*.md" ! -name "README.md" | sort -r)

          # 生成新的 README 内容
          echo "# My Blog" > README.md
          echo "" >> README.md
          echo "## Articles" >> README.md
          echo "" >> README.md

          # 为每个 .md 文件生成链接
          for file in $md_files; do
            filename=$(basename "$file")
            # 提取文件名中的日期部分
            date_part=$(echo "$filename" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}")
            # 按日期倒序排序
            echo "- [${filename%.md}](${filename}) ($date_part)" >> README.md
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README with MD files"
          branch: main
