name: Update README with MD Files

on:
  push:
    paths:
      - "*.md"
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保工作流有写入仓库内容的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          # 获取所有 .md 文件（排除 README.md）
          md_files=$(ls *.md | grep -v "README.md")

          # 提取文件名中的日期部分并按日期排序（最新的排在最前面）
          sorted_files=$(echo "$md_files" | sort -r -t '-' -k 2)

          # 确保 README.md 有写权限
          chmod +w README.md

          # 生成新的 README 内容
          echo "# My Blog" > README.md
          echo "" >> README.md
          echo "## Articles" >> README.md
          echo "" >> README.md

          # 为每个 .md 文件生成链接
          for file in $sorted_files; do
            echo "- [${file%.md}]($file)" >> README.md
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README with MD files"
          branch: main
